DELIMITER $$
DROP PROCEDURE IF EXISTS Info_servidor $$
CREATE PROCEDURE Info_servidor()
BEGIN
	SHOW GLOBAL STATUS LIKE "Uptime";
	SHOW GLOBAL STATUS LIKE "Connections";
	SHOW GLOBAL STATUS LIKE "Threads_connected";
END
$$
